version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      KVM: "N"  # Disable KVM acceleration
        VERSION: "win7"

      DISK_SIZE: "16G"
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
