version: "3"
environment:
  VERSION: "win10"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    devices:
      KVM: "N"  # Disable KVM acceleration
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
